Feat/subdomain redirection
ethersphere/swarm-extension pull request #136
Opened 2022-08-05 11:07 UTC by tomicvladan

#96 #97 #98

2022-09-09 10:36 UTC, nugaon reviewed
I just tried it out with my local build but it does not redirect the `bzz://{content hash}` to the localhost subdomain...

2022-09-09 11:47 UTC, tomicvladan commented
Now it should work. Could you try again?

2022-09-09 13:58 UTC, nugaon commented
one additional thing that we missed out is updating `sandboxListener` in the `bee-api.listener.ts`.
We don't need to apply sandbox on bee responses if the subdomain redirection is used.

2022-09-09 15:00 UTC, nugaon requested changes
it still does not work on my side...
we need to redirect
- `bzz://{swarm hash or ens}/{path}` and
- `https://{cid or ens}.bzz.link/{path}`
to `http://{cid or ens without .eth}.swarm.localhost:{port}/{path}`

2022-09-09 15:14 UTC, nugaon commented
now it seems like it creates a CID from a CID of the `bzz.link` address.
e.g. `bah5acgzaunpsiqopkg7tmibpy2g3jchobzsjinftr4ps7hicxgvjstflnhtq.bzz.link` -> `http://a35f2441cf51bf36202fc68db488ee0e649434b38f1f2f9d02b9aa994cab69e7.swarm.localhost:1633/`

2022-09-12 14:26 UTC, nugaon commented
now, the subdomain is mapped to the swarm hash reference instead of the CID. please check out the desired mapping in [my previous comment](https://github.com/ethersphere/swarm-extension/pull/136#pullrequestreview-1102469999)

2022-09-12 14:40 UTC, nugaon commented on src/background/listener/bee-api.listener.ts
> +        this.redirectToBzzReference(bzzReference, tabId, true)
why do you do that? `cid.bzz.link` also should be mapped to `{cid}.swarm.localhost`

2022-09-12 14:43 UTC, nugaon commented on src/background/listener/bee-api.listener.ts
> +      url = createSubdomainUrl(this._beeApiUrl, subdomain)
here the subdomain is a swarm hash, but u don't transform it into a CID that the swarm.localhost subdomain requires.

2022-09-12 14:44 UTC, nugaon commented on src/background/listener/bee-api.listener.ts
> +  private redirectToBzzReference(bzzReference: string, tabId: number, preventSubdomainRedirection = false) {
remove `preventSubdomainRedirection
```suggestion
  private redirectToBzzReference(bzzReference: string, tabId: number) {
```

2022-09-20 11:44 UTC, nugaon approved these changes
LGTM!

2022-09-22 10:06 UTC, merged